//
//  Amenity.h
//  Magpie
//
//  Created by minh thao nguyen on 5/15/15.
//  Copyright (c) 2015 Magpie. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <Parse/Parse.h>

//all the icon name
extern NSString * const SECTION_BATHROOM_HIGHLIGHT_ICON;
extern NSString * const SECTION_BATHROOM_NORMAL_ICON;
extern NSString * const SECTION_BEDROOM_HIGHLIGHT_ICON;
extern NSString * const SECTION_BEDROOM_NORMAL_ICON;
extern NSString * const SECTION_GENERAL_HIGHLIGHT_ICON;
extern NSString * const SECTION_GENERAL_NORMAL_ICON;
extern NSString * const SECTION_KITCHEN_HIGHLIGHT_ICON;
extern NSString * const SECTION_KITCHEN_NORMAL_ICON;
extern NSString * const SECTION_LIVINGROOM_HIGHLIGHT_ICON;
extern NSString * const SECTION_LIVINGROOM_NORMAL_ICON;

extern NSString * const BATHROOM_TOWEL_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_TOWEL_NORMAL_ICON;
extern NSString * const BATHROOM_TOILET_PAPER_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_TOILET_PAPER_NORMAL_ICON;
extern NSString * const BATHROOM_SHAMPOO_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_SHAMPOO_NORMAL_ICON;
extern NSString * const BATHROOM_HOT_SHOWER_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_HOT_SHOWER_NORMAL_ICON;
extern NSString * const BATHROOM_HAIR_DRYER_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_HAIR_DRYER_NORMAL_ICON;
extern NSString * const BATHROOM_FIRST_AID_HIGHLIGHT_ICON;
extern NSString * const BATHROOM_FIRST_AID_NORMAL_ICON;

extern NSString * const BEDROOM_BED_HIGHLIGHT_ICON;
extern NSString * const BEDROOM_BED_NORMAL_ICON;
extern NSString * const BEDROOM_CLOSET_HIGHLIGHT_ICON;
extern NSString * const BEDROOM_CLOSET_NORMAL_ICON;
extern NSString * const BEDROOM_TV_HIGHLIGHT_ICON;
extern NSString * const BEDROOM_TV_NORMAL_ICON;

extern NSString * const GENERAL_INTERNET_HIGHLIGHT_ICON;
extern NSString * const GENERAL_INTERNET_NORMAL_ICON;
extern NSString * const GENERAL_AIR_CONDITIONING_HIGHLIGHT_ICON;
extern NSString * const GENERAL_AIR_CONDITIONING_NORMAL_ICON;
extern NSString * const GENERAL_HEATING_HIGHLIGHT_ICON;
extern NSString * const GENERAL_HEATING_NORMAL_ICON;
extern NSString * const GENERAL_WASHER_HIGHLIGHT_ICON;
extern NSString * const GENERAL_WASHER_NORMAL_ICON;
extern NSString * const GENERAL_DRYER_HIGHLIGHT_ICON;
extern NSString * const GENERAL_DRYER_NORMAL_ICON;
extern NSString * const GENERAL_FAMILY_FRIENDLY_HIGHLIGHT_ICON;
extern NSString * const GENERAL_FAMILY_FRIENDLY_NORMAL_ICON;
extern NSString * const GENERAL_PET_ALLOWED_HIGHLIGHT_ICON;
extern NSString * const GENERAL_PET_ALLOWED_NORMAL_ICON;
extern NSString * const GENERAL_NO_SMOKING_HIGHLIGHT_ICON;
extern NSString * const GENERAL_NO_SMOKING_NORMAL_ICON;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_HIGHLIGHT_ICON;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_NORMAL_ICON;
extern NSString * const GENERAL_GYM_HIGHLIGHT_ICON;
extern NSString * const GENERAL_GYM_NORMAL_ICON;
extern NSString * const GENERAL_HOT_TUB_HIGHLIGHT_ICON;
extern NSString * const GENERAL_HOT_TUB_NORMAL_ICON;
extern NSString * const GENERAL_POOL_HIGHLIGHT_ICON;
extern NSString * const GENERAL_POOL_NORMAL_ICON;

extern NSString * const KITCHEN_MICROWAVE_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_MICROWAVE_NORMAL_ICON;
extern NSString * const KITCHEN_REFRIGERATOR_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_REFRIGERATOR_NORMAL_ICON;
extern NSString * const KITCHEN_TOASTER_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_TOASTER_NORMAL_ICON;
extern NSString * const KITCHEN_SILVERWARE_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_SILVERWARE_NORMAL_ICON;
extern NSString * const KITCHEN_DISHWARE_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_DISHWARE_NORMAL_ICON;
extern NSString * const KITCHEN_OVEN_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_OVEN_NORMAL_ICON;
extern NSString * const KITCHEN_COFFEE_MAKER_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_COFFEE_MAKER_NORMAL_ICON;
extern NSString * const KITCHEN_DINING_TABLE_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_DINING_TABLE_NORMAL_ICON;
extern NSString * const KITCHEN_SMOKE_DETECTOR_HIGHLIGHT_ICON;
extern NSString * const KITCHEN_SMOKE_DETECTOR_NORMAL_ICON;

extern NSString * const LIVINGROOM_FIREPLACE_HIGHLIGHT_ICON;
extern NSString * const LIVINGROOM_FIREPLACE_NORMAL_ICON;
extern NSString * const LIVINGROOM_SOFA_HIGHLIGHT_ICON;
extern NSString * const LIVINGROOM_SOFA_NORMAL_ICON;
extern NSString * const LIVINGROOM_TV_HIGHLIGHT_ICON;
extern NSString * const LIVINGROOM_TV_NORMAL_ICON;

//all the item id
extern NSString * const BATHROOM_TOWEL_ID;
extern NSString * const BATHROOM_TOILET_PAPER_ID;
extern NSString * const BATHROOM_SHAMPOO_ID;
extern NSString * const BATHROOM_HOT_SHOWER_ID;
extern NSString * const BATHROOM_HAIR_DRYER_ID;
extern NSString * const BATHROOM_FIRST_AID_ID;

extern NSString * const BEDROOM_BED_ID;
extern NSString * const BEDROOM_CLOSET_ID;
extern NSString * const BEDROOM_TV_ID;

extern NSString * const GENERAL_INTERNET_ID;
extern NSString * const GENERAL_AIR_CONDITIONING_ID;
extern NSString * const GENERAL_HEATING_ID;
extern NSString * const GENERAL_WASHER_ID;
extern NSString * const GENERAL_DRYER_ID;
extern NSString * const GENERAL_FAMILY_FRIENDLY_ID;
extern NSString * const GENERAL_PET_ALLOWED_ID;
extern NSString * const GENERAL_NO_SMOKING_ID;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_ID;
extern NSString * const GENERAL_GYM_ID;
extern NSString * const GENERAL_HOT_TUB_ID;
extern NSString * const GENERAL_POOL_ID;

extern NSString * const KITCHEN_MICROWAVE_ID;
extern NSString * const KITCHEN_REFRIGERATOR_ID;
extern NSString * const KITCHEN_TOASTER_ID;
extern NSString * const KITCHEN_SILVERWARE_ID;
extern NSString * const KITCHEN_DISHWARE_ID;
extern NSString * const KITCHEN_OVEN_ID;
extern NSString * const KITCHEN_COFFEE_MAKER_ID;
extern NSString * const KITCHEN_DINING_TABLE_ID;
extern NSString * const KITCHEN_SMOKE_DETECTOR_ID;

extern NSString * const LIVINGROOM_FIREPLACE_ID;
extern NSString * const LIVINGROOM_SOFA_ID;
extern NSString * const LIVINGROOM_TV_ID;

//all the item description id
extern NSString * const BATHROOM_TOWEL_DESCRIPTION_ID;
extern NSString * const BATHROOM_TOILET_PAPER_DESCRIPTION_ID;
extern NSString * const BATHROOM_SHAMPOO_DESCRIPTION_ID;
extern NSString * const BATHROOM_HOT_SHOWER_DESCRIPTION_ID;
extern NSString * const BATHROOM_HAIR_DRYER_DESCRIPTION_ID;
extern NSString * const BATHROOM_FIRST_AID_DESCRIPTION_ID;

extern NSString * const BEDROOM_BED_DESCRIPTION_ID;
extern NSString * const BEDROOM_CLOSET_DESCRIPTION_ID;
extern NSString * const BEDROOM_TV_DESCRIPTION_ID;

extern NSString * const GENERAL_INTERNET_DESCRIPTION_ID;
extern NSString * const GENERAL_AIR_CONDITIONING_DESCRIPTION_ID;
extern NSString * const GENERAL_HEATING_DESCRIPTION_ID;
extern NSString * const GENERAL_WASHER_DESCRIPTION_ID;
extern NSString * const GENERAL_DRYER_DESCRIPTION_ID;
extern NSString * const GENERAL_FAMILY_FRIENDLY_DESCRIPTION_ID;
extern NSString * const GENERAL_PET_ALLOWED_DESCRIPTION_ID;
extern NSString * const GENERAL_NO_SMOKING_DESCRIPTION_ID;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_DESCRIPTION_ID;
extern NSString * const GENERAL_GYM_DESCRIPTION_ID;
extern NSString * const GENERAL_HOT_TUB_DESCRIPTION_ID;
extern NSString * const GENERAL_POOL_DESCRIPTION_ID;

extern NSString * const KITCHEN_MICROWAVE_DESCRIPTION_ID;
extern NSString * const KITCHEN_REFRIGERATOR_DESCRIPTION_ID;
extern NSString * const KITCHEN_TOASTER_DESCRIPTION_ID;
extern NSString * const KITCHEN_SILVERWARE_DESCRIPTION_ID;
extern NSString * const KITCHEN_DISHWARE_DESCRIPTION_ID;
extern NSString * const KITCHEN_OVEN_DESCRIPTION_ID;
extern NSString * const KITCHEN_COFFEE_MAKER_DESCRIPTION_ID;
extern NSString * const KITCHEN_DINING_TABLE_DESCRIPTION_ID;
extern NSString * const KITCHEN_SMOKE_DETECTOR_DESCRIPTION_ID;

extern NSString * const LIVINGROOM_FIREPLACE_DESCRIPTION_ID;
extern NSString * const LIVINGROOM_SOFA_DESCRIPTION_ID;
extern NSString * const LIVINGROOM_TV_DESCRIPTION_ID;

//all the default text
extern NSString * const BATHROOM_TOWEL_NAME;
extern NSString * const BATHROOM_TOILET_PAPER_NAME;
extern NSString * const BATHROOM_SHAMPOO_NAME;
extern NSString * const BATHROOM_HOT_SHOWER_NAME;
extern NSString * const BATHROOM_HAIR_DRYER_NAME;
extern NSString * const BATHROOM_FIRST_AID_NAME;

extern NSString * const BEDROOM_BED_NAME;
extern NSString * const BEDROOM_CLOSET_NAME;
extern NSString * const BEDROOM_TV_NAME;

extern NSString * const GENERAL_INTERNET_NAME;
extern NSString * const GENERAL_AIR_CONDITIONING_NAME;
extern NSString * const GENERAL_HEATING_NAME;
extern NSString * const GENERAL_WASHER_NAME;
extern NSString * const GENERAL_DRYER_NAME;
extern NSString * const GENERAL_FAMILY_FRIENDLY_NAME;
extern NSString * const GENERAL_PET_ALLOWED_NAME;
extern NSString * const GENERAL_NO_SMOKING_NAME;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_NAME;
extern NSString * const GENERAL_GYM_NAME;
extern NSString * const GENERAL_HOT_TUB_NAME;
extern NSString * const GENERAL_POOL_NAME;

extern NSString * const KITCHEN_MICROWAVE_NAME;
extern NSString * const KITCHEN_REFRIGERATOR_NAME;
extern NSString * const KITCHEN_TOASTER_NAME;
extern NSString * const KITCHEN_SILVERWARE_NAME;
extern NSString * const KITCHEN_DISHWARE_NAME;
extern NSString * const KITCHEN_OVEN_NAME;
extern NSString * const KITCHEN_COFFEE_MAKER_NAME;
extern NSString * const KITCHEN_DINING_TABLE_NAME;
extern NSString * const KITCHEN_SMOKE_DETECTOR_NAME;

extern NSString * const LIVINGROOM_SOFA_NAME;
extern NSString * const LIVINGROOM_FIREPLACE_NAME;
extern NSString * const LIVINGROOM_TV_NAME;

//all the selected placeholder text
extern NSString * const BATHROOM_TOWEL_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BATHROOM_TOILET_PAPER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BATHROOM_SHAMPOO_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BATHROOM_HOT_SHOWER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BATHROOM_HAIR_DRYER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BATHROOM_FIRST_AID_SELECTED_PLACEHOLDER_TEXT;

extern NSString * const BEDROOM_BED_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BEDROOM_CLOSET_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const BEDROOM_TV_SELECTED_PLACEHOLDER_TEXT;

extern NSString * const GENERAL_INTERNET_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_AIR_CONDITIONING_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_HEATING_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_WASHER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_DRYER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_FAMILY_FRIENDLY_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_PET_ALLOWED_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_NO_SMOKING_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_GYM_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_HOT_TUB_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const GENERAL_POOL_SELECTED_PLACEHOLDER_TEXT;

extern NSString * const KITCHEN_MICROWAVE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_REFRIGERATOR_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_TOASTER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_SILVERWARE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_DISHWARE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_OVEN_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_COFFEE_MAKER_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_DINING_TABLE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const KITCHEN_SMOKE_DETECTOR_SELECTED_PLACEHOLDER_TEXT;

extern NSString * const LIVINGROOM_SOFA_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const LIVINGROOM_FIREPLACE_SELECTED_PLACEHOLDER_TEXT;
extern NSString * const LIVINGROOM_TV_SELECTED_PLACEHOLDER_TEXT;

//all the default active text
extern NSString * const BATHROOM_TOWEL_DEFAULT_ACTIVE_TEXT;
extern NSString * const BATHROOM_TOILET_PAPER_DEFAULT_ACTIVE_TEXT;
extern NSString * const BATHROOM_SHAMPOO_DEFAULT_ACTIVE_TEXT;
extern NSString * const BATHROOM_HOT_SHOWER_DEFAULT_ACTIVE_TEXT;
extern NSString * const BATHROOM_HAIR_DRYER_DEFAULT_ACTIVE_TEXT;
extern NSString * const BATHROOM_FIRST_AID_DEFAULT_ACTIVE_TEXT;

extern NSString * const BEDROOM_BED_DEFAULT_ACTIVE_TEXT;
extern NSString * const BEDROOM_CLOSET_DEFAULT_ACTIVE_TEXT;
extern NSString * const BEDROOM_TV_DEFAULT_ACTIVE_TEXT;

extern NSString * const GENERAL_INTERNET_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_AIR_CONDITIONING_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_HEATING_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_WASHER_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_DRYER_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_FAMILY_FRIENDLY_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_PET_ALLOWED_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_NO_SMOKING_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_WHEELCHAIR_ACCESSIBLE_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_GYM_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_HOT_TUB_DEFAULT_ACTIVE_TEXT;
extern NSString * const GENERAL_POOL_DEFAULT_ACTIVE_TEXT;

extern NSString * const KITCHEN_MICROWAVE_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_REFRIGERATOR_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_TOASTER_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_SILVERWARE_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_DISHWARE_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_OVEN_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_COFFEE_MAKER_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_DINING_TABLE_DEFAULT_ACTIVE_TEXT;
extern NSString * const KITCHEN_SMOKE_DETECTOR_DEFAULT_ACTIVE_TEXT;

extern NSString * const LIVINGROOM_SOFA_DEFAULT_ACTIVE_TEXT;
extern NSString * const LIVINGROOM_FIREPLACE_DEFAULT_ACTIVE_TEXT;
extern NSString * const LIVINGROOM_TV_DEFAULT_ACTIVE_TEXT;

@interface Amenity : NSObject
+(PFObject *)newAmenityObj;
+(NSArray *)getBathroomAmenities:(PFObject *)amenityObj;
+(NSArray *)getBathroomActiveAmenities:(PFObject *)amenityObj;
+(NSArray *)getBedroomAmenities:(PFObject *)amenityObj;
+(NSArray *)getBedroomActiveAmenities:(PFObject *)amenityObj;
+(NSArray *)getGeneralAmenities:(PFObject *)amenityObj;
+(NSArray *)getGeneralActiveAmenities:(PFObject *)amenityObj;
+(NSArray *)getKitchenAmenities:(PFObject *)amenityObj;
+(NSArray *)getKitchenActiveAmenities:(PFObject *)amenityObj;
+(NSArray *)getLivingroomAmenities:(PFObject *)amenityObj;
+(NSArray *)getLivingroomActiveAmenities:(PFObject *)amenityObj;
@end













